services:
  frontend:
    build: .
    ports:
      - "3000:5173" # Mapea el puerto del contenedor al del PC
    volumes:
      - ./src:/app/src  # <--- Para editar desde fuera con vscode
      - ./public:/app/public
      - /app/node_modules # Evita conflictos entre node_modules local y el del contenedor
    environment:
      # AquÃ­ conectamos con la API
      - VITE_API_URL=https://api.omarmontanares.com/api/
    stdin_open: true # Necesario para que el hot-reload funcione bien en algunos sistemas
    tty: true